# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [7]:
# City Data File (CSV)
data_file = "dataframe.csv"
weather_py_data = pd.read_csv(data_file)
weather_py_data.head()

,City,Country,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Date
0,Mataura,NZ,-46.19,168.86,53.58,82,93,1.21,1597804350
1,Daru,PG,-9.08,143.21,80.26,60,1,9.22,1597804351
2,Ponta do Sol,PT,32.67,-17.10,71.60,78,20,0.96,1597804351
3,Ushuaia,AR,-54.80,-68.30,32.00,90,40,8.05,1597804282
4,New Norfolk,AU,-42.78,147.06,53.01,80,35,1.99,1597804352

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [8]:
## Configure gmaps
gmaps.configure(api_key=g_key)

In [11]:
# Store 'Lat' and 'Lng' into  locations 
locations = weather_py_data[["Latitude", "Longitude"]].astype(float)
# Convert Humidity to float and store
# HINT: be sure to handle NaN values
weather_py_data = weather_data.dropna()
humidity = weather_py_data['Humidity'].astype(float)
weather_py_data.dtypes

City                object
Country             object
Latitude           float64
Longitude          float64
Max Temperature    float64
Humidity             int64
Cloudiness           int64
Wind Speed         float64
Date                 int64
dtype: object

In [13]:
# Create heatmap
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=100, point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [15]:
narrowed_df = weather_py_data.loc[(weather_py_data["Wind Speed"] <= 10) & (weather_py_data["Cloudiness"] == 0) & \
                                   (weather_py_data["Max Temperature"] >= 70) & (weather_py_data["Max Temperature"] <= 80)].dropna()
narrowed_df

,City,Country,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Date
60,Maric√°,BR,-22.92,-42.82,75.20,83,0,2.24,1597804182
65,Noumea,NC,-22.28,166.46,75.20,53,0,8.05,1597804390
125,Fort-Shevchenko,KZ,44.51,50.26,73.71,64,0,5.39,1597804425
179,Koumac,NC,-20.57,164.28,72.91,56,0,6.24,1597804456
236,Sarkand,KZ,45.41,79.92,75.42,20,0,3.06,1597804485
239,Port Macquarie,AU,-31.43,152.92,72.00,30,0,3.00,1597804486
245,Kelvington,CA,52.17,-103.53,70.43,56,0,0.87,1597804490
256,T≈´krah,LY,32.53,20.58,73.74,87,0,1.74,1597804496
286,Puerto Nari√±o,CO,-3.77,-70.38,77.00,100,0,2.06,1597804512
319,Abu Kamal,SY,34.45,40.92,74.70,37,0,9.62,1597804531
402,Guayaramer√≠n,BO,-10.84,-65.36,79.29,39,0,3.04,1597804573
427,Mangai,CD,-4.05,19.53,75.18,74,0,2.44,1597804586
439,Kyren,RU,51.68,102.14,73.11,48,0,1.41,1597804591
447,Jalu,LY,29.03,21.55,76.98,48,0,8.79,1597804595
486,WaddƒÅn,LY,29.16,16.14,77.49,33,0,1.83,1597804614
508,Arrondissement de Bastia,FR,42.67,9.33,75.99,68,0,3.36,1597804485
529,EqbƒÅlƒ´yeh,IR,35.30,51.54,78.01,30,0,6.93,1597804638

In [18]:
params = {
    "radius" : 5000,
    "type"   : "lodging",
    "key"    : g_key
}

In [23]:
hotel_df = narrowed_df
for index, row in hotel_df.iterrows():
    lat = row["Latitude"]
    lng = row["Longitude"]
    params["location"]=f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    hotels = requests.get(base_url, params=params).json()
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]['name']
    except (KeyError, IndexError):
        print("Hotel not found. Skipping...")

Hotel not found. Skipping...

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [24]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [25]:
hotel_df.head()

,City,Country,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed,Date,Hotel Name
60,Maric√°,BR,-22.92,-42.82,75.20,83,0,2.24,1597804182,Marica Hills
65,Noumea,NC,-22.28,166.46,75.20,53,0,8.05,1597804390,H√¥tel Le Lagon
125,Fort-Shevchenko,KZ,44.51,50.26,73.71,64,0,5.39,1597804425,Oasis hotel Bautino
179,Koumac,NC,-20.57,164.28,72.91,56,0,6.24,1597804456,Le Monitel
236,Sarkand,KZ,45.41,79.92,75.42,20,0,3.06,1597804485,–ì–æ—Å—Ç–∏–Ω–∏—Ü–∞ –°–∞—Ä–∫–∞–Ω–¥

In [26]:
# Add marker layer ontop of heat map

# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# Display figure
fig
plt.savefig("vacation_map.png")
fig

Figure(layout=FigureLayout(height='420px'))